In [ ]:
import pandas as pd
import os
import numpy as np

In [ ]:
# working directory check
print(os.getcwd())

C:\Users\Sophie\Desktop

In [ ]:
#read data
df = pd.read_csv("Moon.csv", engine = 'python')

In [ ]:
df

,username,tweet_date,tweet_time,text,favorites,retweets,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,moonriver365,2020-06-15,23:00:07,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2157,786,NaN,NaN,NaN
1,moonriver365,2020-06-15,23:00:06,"오를란도 대통령님, 첫 통화였지만 의미가 큰 통화였습니다. 한국의 ‘디지털 뉴딜’에...",5393,2602,NaN,NaN,NaN
2,moonriver365,2020-06-15,10:40:00,"""우리 한민족이 반드시 같이 공존공영해서 새로운 21세기에 같이 손잡고 세계 일류 ...",5286,3035,NaN,NaN,NaN
3,moonriver365,2020-06-15,8:24:52,남과 북이 함께 돌파구를 찾아 나설 때가 되었습니다. 더는 여건이 좋아지기만 기다릴...,3892,2038,NaN,NaN,NaN
4,moonriver365,2020-06-15,8:24:52,방역 성공이 곧 경제 회복의 지름길입니다. 방역수칙의 철저한 준수는 생명을 지키는 ...,5333,2845,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
777,moonriver365,2017-05-23,6:50:25,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,9353,8460,NaN,NaN,NaN
778,moonriver365,2017-05-18,8:56:37,서로가 서로를 위하고 서로의 아픔을 어루만져주는 대한민국이 새로운 대한민국입니다. ...,6422,5170,NaN,NaN,NaN
779,moonriver365,2017-05-18,8:37:20,"오늘 5.18 민주화운동 37주년을 맞아, 5.18 묘역에 서니 감회가 매우 깊습니...",9393,10087,NaN,NaN,NaN
780,moonriver365,2017-05-14,4:48:55,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",17803,27260,NaN,NaN,NaN
781,moonriver365,2017-05-10,1:22:58,10:10 국립현충원 참배 10:50 국회의장 환담 (국회의장실) 12:00 제19...,3947,3108,NaN,NaN,NaN

In [ ]:
# try to remove columns
df_1 = df.drop([df.columns[0],df.columns[2],df.columns[-1],df.columns[-2],df.columns[-3]], axis =1)

In [ ]:
df_1

,tweet_date,text,favorites,retweets
0,2020-06-15,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2157,786
1,2020-06-15,"오를란도 대통령님, 첫 통화였지만 의미가 큰 통화였습니다. 한국의 ‘디지털 뉴딜’에...",5393,2602
2,2020-06-15,"""우리 한민족이 반드시 같이 공존공영해서 새로운 21세기에 같이 손잡고 세계 일류 ...",5286,3035
3,2020-06-15,남과 북이 함께 돌파구를 찾아 나설 때가 되었습니다. 더는 여건이 좋아지기만 기다릴...,3892,2038
4,2020-06-15,방역 성공이 곧 경제 회복의 지름길입니다. 방역수칙의 철저한 준수는 생명을 지키는 ...,5333,2845
...,...,...,...,...
777,2017-05-23,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,9353,8460
778,2017-05-18,서로가 서로를 위하고 서로의 아픔을 어루만져주는 대한민국이 새로운 대한민국입니다. ...,6422,5170
779,2017-05-18,"오늘 5.18 민주화운동 37주년을 맞아, 5.18 묘역에 서니 감회가 매우 깊습니...",9393,10087
780,2017-05-14,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",17803,27260
781,2017-05-10,10:10 국립현충원 참배 10:50 국회의장 환담 (국회의장실) 12:00 제19...,3947,3108

In [ ]:
df_1 = df_1[pd.notnull(df_1.text)]

In [ ]:
df_1

,tweet_date,text,favorites,retweets
0,2020-06-15,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2157,786
1,2020-06-15,"오를란도 대통령님, 첫 통화였지만 의미가 큰 통화였습니다. 한국의 ‘디지털 뉴딜’에...",5393,2602
2,2020-06-15,"""우리 한민족이 반드시 같이 공존공영해서 새로운 21세기에 같이 손잡고 세계 일류 ...",5286,3035
3,2020-06-15,남과 북이 함께 돌파구를 찾아 나설 때가 되었습니다. 더는 여건이 좋아지기만 기다릴...,3892,2038
4,2020-06-15,방역 성공이 곧 경제 회복의 지름길입니다. 방역수칙의 철저한 준수는 생명을 지키는 ...,5333,2845
...,...,...,...,...
777,2017-05-23,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,9353,8460
778,2017-05-18,서로가 서로를 위하고 서로의 아픔을 어루만져주는 대한민국이 새로운 대한민국입니다. ...,6422,5170
779,2017-05-18,"오늘 5.18 민주화운동 37주년을 맞아, 5.18 묘역에 서니 감회가 매우 깊습니...",9393,10087
780,2017-05-14,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",17803,27260
781,2017-05-10,10:10 국립현충원 참배 10:50 국회의장 환담 (국회의장실) 12:00 제19...,3947,3108

In [ ]:
df_1.to_csv(r'C:\Users\Sophie\Desktop\df_1.csv',encoding='utf-8-sig')
# Check 해보니 중간에 조금 비어 있음  일단 데이터 합치고 날리겠음

In [ ]:
grouped = df_1.groupby('tweet_date')
weighted_avg_func = lambda g: np.average(g['favorites'], weights = None)
avg_fav = pd.DataFrame(grouped.apply(weighted_avg_func))
avg_fav.columns = ['avg_fav']
avg_fav

                 avg_fav
tweet_date
2017-05-10   3947.000000
2017-05-14  17803.000000
2017-05-18   7907.500000
2017-05-23   9353.000000
2017-05-24   6455.000000
...                  ...
2020-06-07   4688.250000
2020-06-08   6512.000000
2020-06-09   5711.000000
2020-06-10   3892.166667
2020-06-15   4412.200000

[435 rows x 1 columns]

In [ ]:
grouped = df_1.groupby('tweet_date')
weighted_avg_func = lambda g: np.average(g['retweets'], weights = None)
avg_ret = pd.DataFrame(grouped.apply(weighted_avg_func))
avg_ret.columns = ['avg_ret']
avg_ret

                 avg_ret
tweet_date
2017-05-10   3108.000000
2017-05-14  27260.000000
2017-05-18   7628.500000
2017-05-23   8460.000000
2017-05-24   6159.500000
...                  ...
2020-06-07   2176.500000
2020-06-08   3625.000000
2020-06-09   2960.000000
2020-06-10   1923.166667
2020-06-15   2261.200000

[435 rows x 1 columns]

In [ ]:
# try to grouping by data
pro_text = df_1[[ df_1.columns[0], df_1.columns[1]]].groupby(df_1.columns[0]).sum().sort_values(by=df_1.columns[0])
pro_text

                                                         text
tweet_date
2017-05-10  10:10 국립현충원 참배 10:50 국회의장 환담 (국회의장실) 12:00 제19...
2017-05-14  찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...
2017-05-18  서로가 서로를 위하고 서로의 아픔을 어루만져주는 대한민국이 새로운 대한민국입니다. ...
2017-05-23  오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...
2017-05-24  광화문1번가'가 활짝 열립니다. '광화문1번가'는 대한민국 최초의 국민인수위원회가 ...
...                                                       ...
2020-06-07  할머니들도 그런 마음이실 겁니다. 협성양로원 할머니들처럼 조심하는 마음들이 있다면,...
2020-06-08  지금의 논란과 시련이 위안부 운동을 발전적으로 승화시키는 계기가 되길 기대합니다. ...
2020-06-09  “위기가 불평등을 키운다는 공식을 반드시 깨겠습니다.” https://www1.pr...
2020-06-10  오늘 민주주의라는 이름의 나무는 어느 나라보다 더 빠르게 자라고 있습니다. 우리의 ...
2020-06-15  Sr. Presidente @JuanOrlandoH, nuestra primera ...

[435 rows x 1 columns]

In [ ]:
# Mid Check
df_merge = pd.concat([pro_text, avg_ret], axis=1, sort= False)
df_mid = pd.concat([df_merge, avg_fav], axis=1, sort= False)
df_mid

,text,avg_ret,avg_fav
tweet_date,,,
2017-05-10,10:10 국립현충원 참배 10:50 국회의장 환담 (국회의장실) 12:00 제19...,3108.000000,3947.000000
2017-05-14,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",27260.000000,17803.000000
2017-05-18,서로가 서로를 위하고 서로의 아픔을 어루만져주는 대한민국이 새로운 대한민국입니다. ...,7628.500000,7907.500000
2017-05-23,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,8460.000000,9353.000000
2017-05-24,광화문1번가'가 활짝 열립니다. '광화문1번가'는 대한민국 최초의 국민인수위원회가 ...,6159.500000,6455.000000
...,...,...,...
2020-06-07,"할머니들도 그런 마음이실 겁니다. 협성양로원 할머니들처럼 조심하는 마음들이 있다면,...",2176.500000,4688.250000
2020-06-08,지금의 논란과 시련이 위안부 운동을 발전적으로 승화시키는 계기가 되길 기대합니다. ...,3625.000000,6512.000000
2020-06-09,“위기가 불평등을 키운다는 공식을 반드시 깨겠습니다.” https://www1.pr...,2960.000000,5711.000000
2020-06-10,오늘 민주주의라는 이름의 나무는 어느 나라보다 더 빠르게 자라고 있습니다. 우리의 ...,1923.166667,3892.166667
2020-06-15,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2261.200000,4412.200000

In [ ]:
df_mid.to_csv(r'C:\Users\Sophie\Desktop\df_mid.csv',encoding='utf-8-sig')
# Check 해보니 중간에 조금 비어 있음  일단 데이터 합치고 날리겠음

In [ ]:
#read data
df_mid2 = pd.read_csv("df_mid.csv", engine = 'python', encoding='utf-8-sig')
df_mid2

,tweet_date,text,avg_ret,avg_fav
0,2017-05-10,10:10 국립현충원 참배 10:50 국회의장 환담 (국회의장실) 12:00 제19...,3108.000000,3947.000000
1,2017-05-14,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",27260.000000,17803.000000
2,2017-05-18,서로가 서로를 위하고 서로의 아픔을 어루만져주는 대한민국이 새로운 대한민국입니다. ...,7628.500000,7907.500000
3,2017-05-23,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,8460.000000,9353.000000
4,2017-05-24,광화문1번가'가 활짝 열립니다. '광화문1번가'는 대한민국 최초의 국민인수위원회가 ...,6159.500000,6455.000000
...,...,...,...,...
430,2020-06-07,"할머니들도 그런 마음이실 겁니다. 협성양로원 할머니들처럼 조심하는 마음들이 있다면,...",2176.500000,4688.250000
431,2020-06-08,지금의 논란과 시련이 위안부 운동을 발전적으로 승화시키는 계기가 되길 기대합니다. ...,3625.000000,6512.000000
432,2020-06-09,“위기가 불평등을 키운다는 공식을 반드시 깨겠습니다.” https://www1.pr...,2960.000000,5711.000000
433,2020-06-10,오늘 민주주의라는 이름의 나무는 어느 나라보다 더 빠르게 자라고 있습니다. 우리의 ...,1923.166667,3892.166667
434,2020-06-15,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2261.200000,4412.200000

In [ ]:
# Outofrange 날리기
df_mid2 = df_mid2.drop(index=0)

In [ ]:
df_mid2['tweet_date'] = pd.to_datetime(df_mid2['tweet_date'])

In [ ]:
df_mid2

,tweet_date,text,avg_ret,avg_fav
1,2017-05-14,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",27260.000000,17803.000000
2,2017-05-18,서로가 서로를 위하고 서로의 아픔을 어루만져주는 대한민국이 새로운 대한민국입니다. ...,7628.500000,7907.500000
3,2017-05-23,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,8460.000000,9353.000000
4,2017-05-24,광화문1번가'가 활짝 열립니다. '광화문1번가'는 대한민국 최초의 국민인수위원회가 ...,6159.500000,6455.000000
5,2017-05-25,관저 창틈에 둥지를 틀고 있던 딱새 새끼들이 성장해서 날아갔습니다. 어미가 물어다 ...,16406.000000,13633.000000
...,...,...,...,...
430,2020-06-07,"할머니들도 그런 마음이실 겁니다. 협성양로원 할머니들처럼 조심하는 마음들이 있다면,...",2176.500000,4688.250000
431,2020-06-08,지금의 논란과 시련이 위안부 운동을 발전적으로 승화시키는 계기가 되길 기대합니다. ...,3625.000000,6512.000000
432,2020-06-09,“위기가 불평등을 키운다는 공식을 반드시 깨겠습니다.” https://www1.pr...,2960.000000,5711.000000
433,2020-06-10,오늘 민주주의라는 이름의 나무는 어느 나라보다 더 빠르게 자라고 있습니다. 우리의 ...,1923.166667,3892.166667
434,2020-06-15,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2261.200000,4412.200000

In [ ]:
df_mid2.isnull().values.any()

False

In [ ]:
df_mid5 = df_mid2.groupby(pd.Grouper(key = df_mid2.columns[0], freq = '7D'))['text'].apply(lambda x: " ".join(x.astype(str)))
df_text = pd.DataFrame(data = df_mid5) 
df_text

                                                         text
tweet_date
2017-05-14  찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...
2017-05-21  오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...
2017-05-28  바다의 날 기념식은 여러모로 의미 깊었습니다. 14년 만에 대통령이 참석해 해양수산...
2017-06-04  영국 런던에서 일어난 연쇄테러는 무고한 민간인과 어린이를 상대로 저질러진 범죄행위입...
2017-06-11  트위터의 잭 도시 님 감사합니다. 앞으로도 트위터를 통해 국민들과 즐겁게 소통하고 ...
...                                                       ...
2020-05-17  서로 믿고 의지하며, 방역에서 세계를 선도하는 대한민국의 자긍심을 계속 이어나가길 ...
2020-05-24  재정이 경제 충격의 파고를 막는 방파제, 경제 회복을 앞당기는 마중물 역할을 해야 ...
2020-05-31  오늘 비상경제회의에서 포스트 코로나 시대를 앞서가기 위한 국가프로젝트로서 한국판 뉴...
2020-06-07  할머니들도 그런 마음이실 겁니다. 협성양로원 할머니들처럼 조심하는 마음들이 있다면,...
2020-06-14  Sr. Presidente @JuanOrlandoH, nuestra primera ...

[162 rows x 1 columns]

In [ ]:
df_text.isnull().values.any()
df_text.to_csv(r'C:\Users\Sophie\Desktop\df_text.csv',encoding='utf-8-sig')
# Check 해보니 중간에 조금 비어 있음  일단 데이터 합치고 날리겠음

In [ ]:
df_ret = df_mid2.groupby(pd.Grouper(key = df_mid2.columns[0], freq = '7D'))['avg_ret'].mean()
df_ret = pd.DataFrame(data = df_ret) 
df_ret

                 avg_ret
tweet_date
2017-05-14  17444.250000
2017-05-21  16838.625000
2017-05-28   4277.500000
2017-06-04   5432.250000
2017-06-11   3397.666667
...                  ...
2020-05-17   2703.956191
2020-05-24   2796.750000
2020-05-31   3243.000000
2020-06-07   2671.166667
2020-06-14   2261.200000

[162 rows x 1 columns]

In [ ]:
df_ret.isnull().values.any()

True

In [ ]:
df_ret.to_csv(r'C:\Users\Sophie\Desktop\df_ret.csv',encoding='utf-8-sig')
# Check 해보니 중간에 조금 비어 있음  일단 데이터 합치고 날리겠음

In [ ]:
df_fav = df_mid2.groupby(pd.Grouper(key = df_mid2.columns[0], freq = '7D'))['avg_fav'].mean()
df_fav = pd.DataFrame(data = df_fav) 
df_fav

                 avg_fav
tweet_date
2017-05-14  12855.250000
2017-05-21  14297.500000
2017-05-28   6269.000000
2017-06-04   6121.750000
2017-06-11   4715.666667
...                  ...
2020-05-17   5205.188571
2020-05-24   5618.750000
2020-05-31   5991.055555
2020-06-07   5200.854167
2020-06-14   4412.200000

[162 rows x 1 columns]

In [ ]:
df_fav.isnull().values.any()

True

In [ ]:
grouped = df_fav.groupby('tweet_date')
weighted_avg_func = lambda g: np.average(g['avg_fav'], weights = None)
df_fav = pd.DataFrame(grouped.apply(weighted_avg_func))
df_fav.columns = ['favorite']
df_fav

                favorite
tweet_date
2017-05-14  12855.250000
2017-05-21  14297.500000
2017-05-28   6269.000000
2017-06-04   6121.750000
2017-06-11   4715.666667
...                  ...
2020-05-17   5205.188571
2020-05-24   5618.750000
2020-05-31   5991.055556
2020-06-07   5200.854167
2020-06-14   4412.200000

[149 rows x 1 columns]

In [ ]:
df_fav.isnull().values.any()

True

In [ ]:
df_text.head(10)

                                                         text
tweet_date
2017-05-14  찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...
2017-05-21  오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...
2017-05-28  바다의 날 기념식은 여러모로 의미 깊었습니다. 14년 만에 대통령이 참석해 해양수산...
2017-06-04  영국 런던에서 일어난 연쇄테러는 무고한 민간인과 어린이를 상대로 저질러진 범죄행위입...
2017-06-11  트위터의 잭 도시 님 감사합니다. 앞으로도 트위터를 통해 국민들과 즐겁게 소통하고 ...
2017-06-18
2017-06-25  6.25 전쟁은 아픈 역사입니다. 한반도 땅 대부분이 전쟁의 참상을 겪었고, 분단의...
2017-07-02  G20 회의를 위해 독일에 도착했습니다. 북한 미사일 발사로 마음이 무겁습니다만 북...
2017-07-09  여민관 집무실 창가에서 청와대 관람 오신 분들께 인사드렸습니다. 찡찡이와 마루 소식...
2017-07-16  대선 때 모아주셨던 문재인 펀드를 오늘 상환해 드렸습니다. 국민들께서 보내주신 큰 ...

In [ ]:
df_fav.head(10)

                 avg_fav
tweet_date
2017-05-14  12855.250000
2017-05-21  14297.500000
2017-05-28   6269.000000
2017-06-04   6121.750000
2017-06-11   4715.666667
2017-06-18           NaN
2017-06-25   6167.000000
2017-07-02   7067.000000
2017-07-09  11691.000000
2017-07-16   6087.000000

In [ ]:
df_ret.head(10)

                 avg_ret
tweet_date
2017-05-14  17444.250000
2017-05-21  16838.625000
2017-05-28   4277.500000
2017-06-04   5432.250000
2017-06-11   3397.666667
2017-06-18           NaN
2017-06-25   4637.333333
2017-07-02   4502.000000
2017-07-09   8922.000000
2017-07-16   4393.000000

In [ ]:
dfdf = pd.concat([df_ret, df_fav], axis=1, join='inner')
result = pd.concat([df_text, dfdf], axis=1, join='inner')

In [ ]:
result

,text,avg_ret,avg_fav
tweet_date,,,
2017-05-14,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",17444.250000,12855.250000
2017-05-21,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,16838.625000,14297.500000
2017-05-28,바다의 날 기념식은 여러모로 의미 깊었습니다. 14년 만에 대통령이 참석해 해양수산...,4277.500000,6269.000000
2017-06-04,영국 런던에서 일어난 연쇄테러는 무고한 민간인과 어린이를 상대로 저질러진 범죄행위입...,5432.250000,6121.750000
2017-06-11,트위터의 잭 도시 님 감사합니다. 앞으로도 트위터를 통해 국민들과 즐겁게 소통하고 ...,3397.666667,4715.666667
...,...,...,...
2020-05-17,"서로 믿고 의지하며, 방역에서 세계를 선도하는 대한민국의 자긍심을 계속 이어나가길 ...",2703.956191,5205.188571
2020-05-24,"재정이 경제 충격의 파고를 막는 방파제, 경제 회복을 앞당기는 마중물 역할을 해야 ...",2796.750000,5618.750000
2020-05-31,오늘 비상경제회의에서 포스트 코로나 시대를 앞서가기 위한 국가프로젝트로서 한국판 뉴...,3243.000000,5991.055555
2020-06-07,"할머니들도 그런 마음이실 겁니다. 협성양로원 할머니들처럼 조심하는 마음들이 있다면,...",2671.166667,5200.854167
2020-06-14,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2261.200000,4412.200000

In [ ]:
result.to_csv(r'C:\Users\Sophie\Desktop\result.csv',encoding='utf-8-sig')
# Check 해보니 중간에 조금 비어 있음  일단 데이터 합치고 날리겠음

In [ ]:
# working directory check
print(os.getcwd())

C:\Users\Sophie\Desktop\Pre_Moon_Tweet

In [ ]:
result = pd.read_csv("result.csv", engine = 'python', encoding='utf-8-sig')
realmeter = pd.read_csv("realmeter.csv", engine = 'python')

In [ ]:
result

,tweet_date,text,avg_ret,avg_fav
0,2017-05-14,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",17444.250000,12855.250000
1,2017-05-21,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,16838.625000,14297.500000
2,2017-05-28,바다의 날 기념식은 여러모로 의미 깊었습니다. 14년 만에 대통령이 참석해 해양수산...,4277.500000,6269.000000
3,2017-06-04,영국 런던에서 일어난 연쇄테러는 무고한 민간인과 어린이를 상대로 저질러진 범죄행위입...,5432.250000,6121.750000
4,2017-06-11,트위터의 잭 도시 님 감사합니다. 앞으로도 트위터를 통해 국민들과 즐겁게 소통하고 ...,3397.666667,4715.666667
...,...,...,...,...
157,2020-05-17,"서로 믿고 의지하며, 방역에서 세계를 선도하는 대한민국의 자긍심을 계속 이어나가길 ...",2703.956191,5205.188571
158,2020-05-24,"재정이 경제 충격의 파고를 막는 방파제, 경제 회복을 앞당기는 마중물 역할을 해야 ...",2796.750000,5618.750000
159,2020-05-31,오늘 비상경제회의에서 포스트 코로나 시대를 앞서가기 위한 국가프로젝트로서 한국판 뉴...,3243.000000,5991.055555
160,2020-06-07,"할머니들도 그런 마음이실 겁니다. 협성양로원 할머니들처럼 조심하는 마음들이 있다면,...",2671.166667,5200.854167
161,2020-06-14,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2261.200000,4412.200000

In [ ]:
realmeter

            조사 기간      긍정      부정
0     2017년 5월 3주  81.60%  10.10%
1     2017년 5월 4주  84.10%  10.00%
2     2017년 5월 5주  78.10%  14.20%
3     2017년 6월 1주  78.90%  14.70%
4     2017년 6월 2주  75.60%  17.40%
..            ...     ...     ...
179  2020년 11월 2주  44.30%  51.00%
180  2020년 11월 3주  42.70%  53.00%
181  2020년 11월 4주  43.80%  52.20%
182  2020년 12월 1주  37.40%  57.40%
183  2020년 12월 2주  36.70%  58.20%

[184 rows x 3 columns]

In [ ]:
final = pd.concat([realmeter, result], axis=1, join='inner')
final

,조사 기간,긍정,부정,tweet_date,text,avg_ret,avg_fav
0,2017년 5월 3주,81.60%,10.10%,2017-05-14,"찡찡이가 입주했는데,걱정이 생겼네요. 관저 구석의 유리창문과 미닫이 한지창문 사이의...",17444.250000,12855.250000
1,2017년 5월 4주,84.10%,10.00%,2017-05-21,오늘 이 추도식에 대통령으로 참석하겠다고 한 약속을 지킬 수 있게 해주신 것에 대해...,16838.625000,14297.500000
2,2017년 5월 5주,78.10%,14.20%,2017-05-28,바다의 날 기념식은 여러모로 의미 깊었습니다. 14년 만에 대통령이 참석해 해양수산...,4277.500000,6269.000000
3,2017년 6월 1주,78.90%,14.70%,2017-06-04,영국 런던에서 일어난 연쇄테러는 무고한 민간인과 어린이를 상대로 저질러진 범죄행위입...,5432.250000,6121.750000
4,2017년 6월 2주,75.60%,17.40%,2017-06-11,트위터의 잭 도시 님 감사합니다. 앞으로도 트위터를 통해 국민들과 즐겁게 소통하고 ...,3397.666667,4715.666667
...,...,...,...,...,...,...,...
157,2020년 6월 2주,58.20%,37.00%,2020-05-17,"서로 믿고 의지하며, 방역에서 세계를 선도하는 대한민국의 자긍심을 계속 이어나가길 ...",2703.956191,5205.188571
158,2020년 6월 3주,53.40%,41.80%,2020-05-24,"재정이 경제 충격의 파고를 막는 방파제, 경제 회복을 앞당기는 마중물 역할을 해야 ...",2796.750000,5618.750000
159,2020년 6월 4주,53.30%,42.70%,2020-05-31,오늘 비상경제회의에서 포스트 코로나 시대를 앞서가기 위한 국가프로젝트로서 한국판 뉴...,3243.000000,5991.055555
160,2020년 7월 1주,49.80%,45.50%,2020-06-07,"할머니들도 그런 마음이실 겁니다. 협성양로원 할머니들처럼 조심하는 마음들이 있다면,...",2671.166667,5200.854167
161,2020년 7월 2주,48.70%,46.50%,2020-06-14,"Sr. Presidente @JuanOrlandoH, nuestra primera ...",2261.200000,4412.200000

In [ ]:
final.to_csv(r'C:\Users\Sophie\Desktop\final_pre.csv',encoding='utf-8-sig')

In [ ]:
# 날짜가 맞지 않는 것이 있어서 csv 오픈해서 날짜를 좀 조정 했다!